package com.unicorn.juror.registration.nation

import com.unicorn.juror.util.Label

class Nation {

    companion object {

        fun list() = listOf(
                Label("汉族", "1"),
                Label(" 蒙古族", "2"),
                Label(" 回族	", "3"),
                Label(" 藏族	", "4"),
                Label(" 维吾尔族", "5"),
                Label(" 苗族	", "6"),
                Label(" 彝族	", "7"),
                Label(" 壮族	", "8"),
                Label(" 布依族", "9"),
                Label(" 朝鲜族", "10"),
                Label(" 满族	", "11"),
                Label(" 侗族	", "12"),
                Label(" 瑶族	", "13"),
                Label(" 白族	", "14"),
                Label(" 土家族", "15"),
                Label(" 哈尼族", "16"),
                Label(" 哈萨克族", "17"),
                Label(" 傣族	", "18"),
                Label(" 黎族	", "19"),
                Label(" 傈僳族", "20"),
                Label(" 佤族	", "21"),
                Label(" 畲族	", "22"),
                Label(" 高山族", "23"),
                Label(" 拉祜族", "24"),
                Label(" 水族	", "25"),
                Label(" 东乡族", "26"),
                Label(" 纳西族", "27"),
                Label(" 景颇族", "28"),
                Label(" 柯尔克孜族", "29"),
                Label(" 土族	", "30"),
                Label(" 达斡尔族", "31"),
                Label(" 仫佬族", "32"),
                Label(" 羌族	", "33"),
                Label(" 布郎族", "34"),
                Label(" 撒拉族", "35"),
                Label(" 毛难族", "36"),
                Label(" 仡佬族", "37"),
                Label(" 锡伯族", "38"),
                Label(" 阿昌族", "39"),
                Label(" 普米族", "40"),
                Label(" 塔吉克族", "41"),
                Label(" 怒族	", "42"),
                Label(" 乌孜别克族", "43"),
                Label(" 俄罗斯族", "44"),
                Label(" 鄂温克族", "45"),
                Label(" 崩龙族", "46"),
                Label(" 保安族", "47"),
                Label(" 裕固族", "48"),
                Label(" 京族	", "49"),
                Label(" 塔塔尔族", "50"),
                Label(" 独龙族", "51"),
                Label(" 鄂伦春族", "52"),
                Label(" 赫哲族", "53"),
                Label(" 门巴族", "54"),
                Label(" 珞巴族", "55"),
                Label(" 基诺族", "56"),
                Label(" 其他	", "97"),
                Label(" 外国血统", "98"),
                Label(" 外籍人员", "99"),
                Label(" 无国籍人员", "100"),
                Label(" 香港人", "101"),
                Label(" 澳门人", "102"),
                Label(" 台湾人", "103"),
                Label(" 华侨	", "104")
        )
    }

}